### ISSUE TITLE
Setup Process API, Keys, Secrets

### ISSUE THREAD

**Issue by VolantTyler** [chingu-voyage7/Geckos-Team-18#19]
I am having difficulty setting up the project on my local machine. This may be either my misunderstanding or an error in documentation: I acquired my mLab API key, but I do not see an option to get an mLab secret key. mLab support documentation does not shed any light on this, except an article (https://v1.api.mlab.com/docs/) that links to a "page not found". 

Also, do we need to have an account with Sendgrid to get an API key to run this program?

**Comment by drunkenkismet** [comment]
My bad on that -- the README was definitely unclear (I threw it together rather quickly, but I intended to go back soon to update/clarify various pieces). The `secret` key is entirely up to you and is unrelated to mLab, as you likely discovered. Instead, it's used once in a user's initial session authentication with the app. Look in the root directory's `routes` > `api` > `users.js`  file, roughly line 116 where it's assigned as part of the `jwt.sign` method's second argument. And, yes, the SendGrid API key requires an account. To the best of my understanding, it's free -- there are approximately 1,000 emails afforded during the first month, after which it drops to (don't quote me on this) 200 per month, barring paying for usage.
